apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: nginx
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environment: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        ports:
        - name: nginx-port
          containerPort: 3000
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: db-secrets
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db-secrets
        livenessProbe:
          httpGet:
            path: /live
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 15